### ISSUE TITLE
Unit tests fail when running with nyc

### ISSUE THREAD

**Issue by kinwa91** [googleapis/gcs-resumable-upload#157]
Tests are [failing](https://source.cloud.google.com/results/invocations/4c559183-966f-43bf-946f-7ca2915bc22f/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fgcs-resumable-upload%2Fnode6%2Ftest/log) and locally as well.

But when running `mocha` without `nyc`, the tests pass.

**Comment by kinwa91** [comment]
```
      1) should set the callback to a noop
(node:37876) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- '()=>{cov_278bwfikq5.f[21]++;}'
+ '() => { }'
    at up.getRequestStream (/Users/jonathanlui/gcs-resumable-upload/test/test.ts:887:20)
    at authClient.getRequestHeaders.then.authHeaders (/Users/jonathanlui/gcs-resumable-upload/src/index.ts:160:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:37876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

Looks like some code is being injected by `nyc`
