### ISSUE TITLE
Should uploading not use async internally instead of sync?

### ISSUE THREAD

**Issue by Christilut** [googleapis/gcs-resumable-upload#297]
I just ran my nodejs express server with the ` --trace-sync-io` flag that prints synchronous calls and I see tons of these when uploading a file through Firebase Storage:
```
(node:10320) WARNING: Detected use of sync API
    at openSync (fs.js:437:26)
    at readFileSync (fs.js:342:35)
    at get all (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:34:25)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:81:23)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:352:26)
    at onChunk (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:237:22)
    at Transform._read (_stream_transform.js:189:10)
    at Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
(node:10320) WARNING: Detected use of sync API
    at tryStatSync (fs.js:304:25)
    at readFileSync (fs.js:344:17)
    at get all (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:34:25)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/node_modules/configstore/index.js:81:23)
    at set (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:352:26)
    at onChunk (/home/alpha/workspace/rekordcloud-api/node_modules/gcs-resumable-upload/build/src/index.js:237:22)
    at Transform._read (_stream_transform.js:189:10)
    at Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:431:12)
```

Should these calls not be async instead? Is there a reason that they are all sync?

**Comment by Christilut** [comment]
I made a super minimal repro [here](https://github.com/Christilut/gcp-storage-sync). Just add credentials and project id to `.env` and run with `npm run dev`

On startup it already has lots of sync messages. And then for every request quite a few more.

**Comment by frankyn** [comment]
@stephenplusplus do you have cycles to help look at this?

**Comment by stephenplusplus** [comment]
@Christilut I'm not very familiar with accessing Storage through Firebase. I was able to start up the app using "node ./" from your sample, and hit the URL, but it just performs the operations without any logging.

**Comment by Christilut** [comment]
@stephenplusplus Make sure to run `npm run dev` because it will enable the trace logging

**Comment by stephenplusplus** [comment]
Thanks, sorry I didn't see that. I think this is something that's just to be expected by requirements here. The logging output is lengthy, but a lot of that shows the require statements of various modules as they load their dependencies, and they load theirs, etc. I was worried we were accidentally making multiple calls where we only meant to make one, but that doesn't appear to be happening.

The `configstore` library we use intentionally chose atomic writes (https://github.com/yeoman/configstore/issues/20), which requires the use of the synchronous APIs. That library uses `graceful-fs` and `write-file-atomic`, which are responsible for calling the various `fs` sync APIs involved in opening, reading, writing, closing, and deleting the files.

A way around this would be to avoid using the disk as the config store, brought up in #347. That would remove the sync usage and instead allow the user to plug-in their own config store mechanism.

@frankyn I believe we can close this issue and leave #347 to be an ultimate solution to this.

Let me know what you guys think, and if I missed anything. Thanks!

**Comment by frankyn** [comment]
Thanks @stephenplusplus, I don't have permission to close the issue, could you when you have a moment?

@Christilut PLUK if this does not answer your question.
