### ISSUE TITLE
Truncated exponential backoff for "408 Request Timeout"

### ISSUE THREAD

**Issue by romadomma** [googleapis/gcs-resumable-upload#397]
Sometimes I get the error **408 Request timeout** when resuming a file uploading . 
The documentation says that you can use [Truncated exponential backoff](https://cloud.google.com/storage/docs/exponential-backoff) for this case. But [the code for retries](https://github.com/googleapis/gcs-resumable-upload/blob/e76fe4a9b2809c9cc87f5ea1ad0af9ed26885ecc/src/index.ts#L639) ignores this response code.
Maybe you can add this? Thanks!

**Comment by stephenplusplus** [comment]
I'm not sure which code path returns that error. Is it possible you have a stacktrace or a way to reproduce?

If it's one of the simpler requests, basically getting metadata, we should retry that. If it's returned during the progressive upload from a stream, we're a bit stuck there. If we already passed the data up to the server, we aren't able to rewind and get it back.

**Comment by romadomma** [comment]
```
Error: Upload failed
    at Upload.<anonymous> (/app/node_modules/gcs-resumable-upload/build/src/index.js:191:30)
    at Upload.emit (events.js:228:7)
    at Upload.EventEmitter.emit (domain.js:475:20)
    at Upload.onResponse (/app/node_modules/gcs-resumable-upload/build/src/index.js:388:14)
    at Upload.makeRequestStream (/app/node_modules/gcs-resumable-upload/build/src/index.js:337:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Upload.startUploading (/app/node_modules/gcs-resumable-upload/build/src/index.js:219:13)
```
The **onRequest** function in the stack

**Comment by danielduhh** [comment]
Hey @romadomma thanks for highlight this. 408 resumable media response codes and considered [retriable](https://cloud.google.com/storage/docs/retry-strategy) & we plan to fix this inconsistency soon (see [draft pr](https://github.com/googleapis/nodejs-storage/pull/1476) in GCS node-storage repo).

**Comment by shaffeeullah** [comment]
https://github.com/googleapis/gcs-resumable-upload/pull/441 creates the infrastructure for us to pass in a function with all the documented retryable error codes from `nodejs-common`.
